-- Roles preestablecidos
INSERT INTO
    roles (role_name)
VALUES
    ('default'),
    ('reportero'),
    ('validador'),
    ('admin');

-- Usuarios
INSERT INTO
    users (username, email, phone, password_hash)
VALUES
    (
        'Juan Perez',
        'juan.perez@email.com',
        '5551234567',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Maria Gomez',
        'maria.gomez@email.com',
        '5552345678',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Carlos Lopez',
        'carlos.lopez@email.com',
        '5553456789',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Ana Martinez',
        'ana.martinez@email.com',
        '5554567890',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Luis Rodriguez',
        'luis.rodriguez@email.com',
        '5555678901',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Sofia Hernandez',
        'sofia.hernandez@email.com',
        '5556789012',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Pedro Garcia',
        'pedro.garcia@email.com',
        '5557890123',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Laura Diaz',
        'laura.diaz@email.com',
        '5558901234',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Jorge Sanchez',
        'jorge.sanchez@email.com',
        '5559012345',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    ),
    (
        'Elena Ruiz',
        'elena.ruiz@email.com',
        '5550123456',
        '$2y$10$Hhid4w2e2ZQ7SA3uVQxrE.7XlWcB7kUfJWJWfJQmYJZzYdLQ5Q5Oq'
    );

-- Roles de usuarios
INSERT INTO
    user_roles (user_id, role_id)
VALUES
    (1, 1),
    (1, 2),
    (2, 1),
    (2, 3),
    (3, 1),
    (4, 1),
    (4, 2),
    (5, 1),
    (5, 4),
    (6, 1),
    (6, 2),
    (7, 1),
    (8, 1),
    (8, 3),
    (9, 1),
    (10, 1),
    (10, 2);

-- Provincias
INSERT INTO
    provinces (province_name)
VALUES
    ('Azua'),
    ('Bahoruco'),
    ('Barahona'),
    ('Dajabón'),
    ('Distrito Nacional'),
    ('Duarte'),
    ('Elías Piña'),
    ('El Seibo'),
    ('Espaillat'),
    ('Hato Mayor'),
    ('Hermanas Mirabal'),
    ('Independencia'),
    ('La Altagracia'),
    ('La Romana'),
    ('La Vega'),
    ('María Trinidad Sánchez'),
    ('Monseñor Nouel'),
    ('Monte Cristi'),
    ('Monte Plata'),
    ('Pedernales'),
    ('Peravia'),
    ('Puerto Plata'),
    ('Samaná'),
    ('Sánchez Ramírez'),
    ('San Cristóbal'),
    ('San José de Ocoa'),
    ('San Juan'),
    ('San Pedro de Macorís'),
    ('Santiago'),
    ('Santiago Rodríguez'),
    ('Santo Domingo'),
    ('Valverde');

-- Municipios
INSERT INTO
    municipalities (municipality_name, province_id)
VALUES
    ('Distrito Nacional', 5),
    ('Azua de Compostela', 1),
    ('Estebanía', 1),
    ('Guayabal', 1),
    ('Las Charcas', 1),
    ('Las Yayas de Viajama', 1),
    ('Padre Las Casas', 1),
    ('Peralta', 1),
    ('Pueblo Viejo', 1),
    ('Sabana Yegua', 1),
    ('Tábara Arriba', 1),
    ('Neiba', 2),
    ('Galván', 2),
    ('Los Ríos', 2),
    ('Tamayo', 2),
    ('Villa Jaragua', 2),
    ('Barahona', 3),
    ('Cabral', 3),
    ('El Peñón', 3),
    ('Enriquillo', 3),
    ('Fundación', 3),
    ('Jaquimeyes', 3),
    ('La Ciénaga', 3),
    ('Las Salinas', 3),
    ('Paraíso', 3),
    ('Polo', 3),
    ('Vicente Noble', 3),
    ('Dajabón', 4),
    ('El Pino', 4),
    ('Loma de Cabrera', 4),
    ('Partido', 4),
    ('Restauración', 4),
    ('San Francisco de Macorís', 6),
    ('Arenoso', 6),
    ('Castillo', 6),
    ('Eugenio María de Hostos', 6),
    ('Las Guáranas', 6),
    ('Pimentel', 6),
    ('Villa Riva', 6),
    ('El Seibo', 8),
    ('Miches', 8),
    ('Comendador', 7),
    ('Bánica', 7),
    ('El Llano', 7),
    ('Hondo Valle', 7),
    ('Juan Santiago', 7),
    ('Pedro Santana', 7),
    ('Moca', 9),
    ('Cayetano Germosén', 9),
    ('Gaspar Hernández', 9),
    ('Jamao al Norte', 9),
    ('Hato Mayor del Rey', 10),
    ('El Valle', 10),
    ('Sabana de la Mar', 10),
    ('Salcedo', 11),
    ('Tenares', 11),
    ('Villa Tapia', 11),
    ('Jimaní', 12),
    ('Cristóbal', 12),
    ('Duvergé', 12),
    ('La Descubierta', 12),
    ('Mella', 12),
    ('Postrer Río', 12),
    ('Higüey', 13),
    ('San Rafael del Yuma', 13),
    ('La Romana', 14),
    ('Guaymate', 14),
    ('Villa Hermosa', 14),
    ('La Concepción de La Vega', 15),
    ('Constanza', 15),
    ('Jarabacoa', 15),
    ('Jima Abajo', 15),
    ('Nagua', 16),
    ('Cabrera', 16),
    ('El Factor', 16),
    ('Río San Juan', 16),
    ('Bonao', 17),
    ('Maimón', 17),
    ('Piedra Blanca', 17),
    ('Montecristi', 18),
    ('Castañuela', 18),
    ('Guayubín', 18),
    ('Las Matas de Santa Cruz', 18),
    ('Pepillo Salcedo', 18),
    ('Villa Vásquez', 18),
    ('Monte Plata', 19),
    ('Bayaguana', 19),
    ('Peralvillo', 19),
    ('Sabana Grande de Boyá', 19),
    ('Yamasá', 19),
    ('Pedernales', 20),
    ('Oviedo', 20),
    ('Baní', 21),
    ('Nizao', 21),
    ('Puerto Plata', 22),
    ('Altamira', 22),
    ('Guananico', 22),
    ('Imbert', 22),
    ('Los Hidalgos', 22),
    ('Luperón', 22),
    ('Sosúa', 22),
    ('Villa Isabela', 22),
    ('Villa Montellano', 22),
    ('Samaná', 23),
    ('Las Terrenas', 23),
    ('Sánchez', 23),
    ('San Cristóbal', 25),
    ('Bajos de Haina', 25),
    ('Cambita Garabito', 25),
    ('Los Cacaos', 25),
    ('Sabana Grande de Palenque', 25),
    ('San Gregorio de Nigua', 25),
    ('Villa Altagracia', 25),
    ('Yaguate', 25),
    ('San José de Ocoa', 26),
    ('Rancho Arriba', 26),
    ('Sabana Larga', 26),
    ('San Juan de la Maguana', 27),
    ('Bohechío', 27),
    ('El Cercado', 27),
    ('Juan de Herrera', 27),
    ('Las Matas de Farfán', 27),
    ('Vallejuelo', 27),
    ('San Pedro de Macorís', 28),
    ('Consuelo', 28),
    ('Guayacanes', 28),
    ('Quisqueya', 28),
    ('Ramón Santana', 28),
    ('San José de Los Llanos', 28),
    ('Cotuí', 24),
    ('Cevicos', 24),
    ('Fantino', 24),
    ('La Mata', 24),
    ('Santiago', 29),
    ('Bisonó', 29),
    ('Jánico', 29),
    ('Licey al Medio', 29),
    ('Puñal', 29),
    ('Sabana Iglesia', 29),
    ('San José de las Matas', 29),
    ('Tamboril', 29),
    ('Villa González', 29),
    ('San Ignacio de Sabaneta', 30),
    ('Los Almácigos', 30),
    ('Monción', 30),
    ('Santo Domingo Este', 31),
    ('Boca Chica', 31),
    ('Los Alcarrizos', 31),
    ('Pedro Brand', 31),
    ('San Antonio de Guerra', 31),
    ('Santo Domingo Norte', 31),
    ('Santo Domingo Oeste', 31),
    ('Mao', 32),
    ('Esperanza', 32),
    ('Laguna Salada', 32);

-- Barrios
INSERT INTO
    neighborhoods (neighborhood_name, municipality_id)
VALUES
    ('Barreras', 2),
    ('Barro Arriba', 2),
    ('Clavellina', 2),
    ('Emma Balaguer Viuda Vallejo', 2),
    ('Las Barías-La Estancia', 2),
    ('Las Lomas', 2),
    ('Los Jovillos', 2),
    ('Puerto Viejo', 2),
    ('Hatillo', 5),
    ('Palmar de Ocoa', 5),
    ('Villarpando', 6),
    ('Hato Nuevo-Cortés', 6),
    ('La Siembra', 7),
    ('Los Fríos', 7),
    ('El Rosario', 9),
    ('Proyecto 4', 10),
    ('Ganadero', 10),
    ('Proyecto 2-C', 10),
    ('Amiama Gómez', 11),
    ('Los Toros', 11),
    ('Tábara Abajo', 11),
    ('El Palmar', 12),
    ('El Salado', 13),
    ('Las Clavellinas', 14),
    ('Cabeza de Toro', 15),
    ('Mena', 15),
    ('Monserrat', 15),
    ('Santa Bárbara-El 6', 15),
    ('Santana', 15),
    ('Uvilla', 15),
    ('El Cachón', 17),
    ('La Guázara', 17),
    ('Villa Central', 17),
    ('Arroyo Dulce', 20),
    ('Pescadería', 21),
    ('Palo Alto', 22),
    ('Bahoruco', 23),
    ('Los Patos', 25),
    ('Canoa', 27),
    ('Fondo Negro', 27),
    ('Quita Coraza', 27),
    ('Cañongo', 28),
    ('Manuel Bueno', 4),
    ('Capotillo', 30),
    ('Santiago de la Cruz', 30),
    ('Cenoví', 33),
    ('Jaya', 33),
    ('La Peña', 33),
    ('Presidente Don Antonio Guzmán Fernández', 33),
    ('Aguacate', 34),
    ('Las Coles', 34),
    ('Sabana Grande', 36),
    ('Agua Santa del Yuna', 39),
    ('Barraquito', 39),
    ('Cristo Rey de Guaraguao', 39),
    ('Las Táranas', 39),
    ('Pedro Sánchez', 40),
    ('San Francisco-Vicentillo', 40),
    ('Santa Lucía', 41),
    ('El Cedro', 41),
    ('La Gina', 41),
    ('Guayabo', 42),
    ('Sabana Larga', 42),
    ('Sabana Cruz', 43),
    ('Sabana Higüero', 43),
    ('Guanito', 44),
    ('Rancho de la Guardia', 45),
    ('Río Limpio', 47),
    ('Canca La Reina', 48),
    ('El Higüerito', 48),
    ('José Contreras', 48),
    ('Juan López', 48),
    ('La Ortega', 48),
    ('Las Lagunas', 48),
    ('Monte de la Jagua', 48),
    ('San Víctor', 48),
    ('Joba Arriba', 50),
    ('Veragua', 50),
    ('Villa Magante', 50),
    ('Guayabo Dulce', 52),
    ('Mata Palacio', 52),
    ('Yerba Buena', 52),
    ('Elupina Cordero de Las Cañitas', 54),
    ('Jamao Afuera', 55),
    ('Blanco', 56),
    ('Boca de Cachón', 58),
    ('El Limón', 58),
    ('Batey 8', 59),
    ('Vengan a Ver', 60),
    ('La Colonia', 62),
    ('Guayabal', 63),
    ('La Otra Banda', 64),
    ('Lagunas de Nisibón', 64),
    ('Verón-Punta Cana', 64),
    ('Bayahibe', 65),
    ('Boca de Yuma', 65),
    ('Caleta', 66),
    ('Cumayasa', 68),
    ('El Ranchito', 69),
    ('Río Verde Arriba', 69),
    ('La Sabina', 70),
    ('Tireo', 70),
    ('Buena Vista', 70),
    ('Manabao', 71),
    ('Rincón', 72),
    ('Arroyo al Medio', 73),
    ('Las Gordas', 73),
    ('San José de Matanzas', 73),
    ('Arroyo Salado', 74),
    ('La Entrada', 74),
    ('El Pozo', 75),
    ('Arroyo Toro-Masipedro', 77),
    ('La Salvia-Los Quemados', 77),
    ('Jayaco', 77),
    ('Juma Bejucal', 77),
    ('Sabana del Puerto', 77),
    ('Juan Adrián', 79),
    ('Villa Sonador', 79),
    ('Palo Verde', 81),
    ('Cana Chapetón', 82),
    ('Hatillo Palma', 82),
    ('Villa Elisa', 82),
    ('Boyá', 86),
    ('Chirino', 86),
    ('Don Juan', 86),
    ('Gonzalo', 89),
    ('Majagual', 89),
    ('Los Botados', 90),
    ('José Francisco Peña Gómez', 91),
    ('Juancho', 91),
    ('Catalina', 93),
    ('El Carretón', 93),
    ('El Limonal', 93),
    ('Las Barías', 93),
    ('Matanzas', 93),
    ('Paya', 93),
    ('Sabana Buey', 93),
    ('Villa Fundación', 93),
    ('Villa Sombrero', 93),
    ('Pizarrete', 94),
    ('Santana', 94),
    ('Maimón', 86),
    ('Yásica Arriba', 86),
    ('Río Grande', 96),
    ('Navas', 99),
    ('Belloso', 100),
    ('Estrecho', 100),
    ('La Isabela', 100),
    ('Cabarete', 101),
    ('Sabaneta de Yásica', 101),
    ('Estero Hondo', 102),
    ('Gualete', 102),
    ('La Jaiba', 102),
    ('Arroyo Barril', 104),
    ('El Limón', 104),
    ('Las Galeras', 104),
    ('Hato Damas', 107),
    ('El Carril', 108),
    ('Cambita El Pueblecito', 109),
    ('La Cuchilla', 113),
    ('Medina', 113),
    ('San José del Puerto', 113),
    ('El Naranjal', 115),
    ('El Pinar', 115),
    ('La Ciénaga', 115),
    ('Nizao-Las Auyamas', 115),
    ('El Rosario', 118),
    ('Guanito', 118),
    ('Hato del Padre', 118),
    ('Hato Nuevo', 118),
    ('La Jagua', 118),
    ('Las Charcas de María Nova', 118),
    ('Pedro Corto', 118),
    ('Sabana Alta', 118),
    ('Sabaneta', 118),
    ('Arroyo Cano', 119),
    ('Yaque', 119),
    ('Batista', 120),
    ('Derrumbadero', 120),
    ('Jínova', 121),
    ('Carrera de Yegua', 122),
    ('Matayaya', 122),
    ('Jorjillo', 123),
    ('El Puerto', 129),
    ('Gautier', 129),
    ('Caballero', 130),
    ('Comedero Arriba', 130),
    ('Quita Sueño', 130),
    ('La Cueva', 131),
    ('Platanal', 131),
    ('Angelina', 133),
    ('La Bija', 133),
    ('Hernando Alonzo', 133),
    ('Baitoa', 134),
    ('Hato del Yaque', 134),
    ('La Canela', 134),
    ('Pedro García', 134),
    ('San Francisco de Jacagua', 134),
    ('El Caimito', 136),
    ('Juncalito', 136),
    ('Las Palomas', 137),
    ('Canabacoa', 137),
    ('Guayabal', 137),
    ('El Rubio', 140),
    ('La Cuesta', 140),
    ('Las Placetas', 140),
    ('Canca La Piedra', 141),
    ('El Limón', 142),
    ('Palmar Arriba', 142),
    ('San Luis', 146),
    ('La Caleta', 147),
    ('Palmarejo-Villa Linda', 148),
    ('Pantoja', 148),
    ('La Cuaba', 149),
    ('La Guáyiga', 149),
    ('Hato Viejo', 150),
    ('La Victoria', 151),
    ('Ámina', 153),
    ('Guatapanal', 153),
    ('Jaibón (Pueblo Nuevo)', 153),
    ('Boca de Mao', 154),
    ('Jicomé', 154),
    ('Maizal', 154),
    ('Paradero', 154),
    ('Cruce de Guayacanes', 155),
    ('Jaibón', 155),
    ('La Caya', 155);

-- Incidencias
INSERT INTO
    incidents (
        title,
        incidence_description,
        occurrence_date,
        latitude,
        longitude,
        is_approved,
        n_deaths,
        n_injured,
        n_losses,
        province_id,
        municipality_id,
        neighborhood_id,
        user_id,
        creation_date
    )
VALUES
    (
        'Accidente múltiple en Av. 27 de Febrero',
        'Colisión entre 3 vehículos en la avenida. Se reportan heridos.',
        '2023-11-01 08:30:00',
        18.4861,
        -69.9312,
        1,
        0,
        3,
        15000.00,
        1,
        1,
        1,
        1,
        '2023-11-01 09:15:00'
    ),
    (
        'Robo en colmado de Villa Mella',
        'Dos sujetos armados robaron efectivo y mercancía.',
        '2023-11-02 22:45:00',
        18.5667,
        -69.9833,
        1,
        0,
        1,
        5000.00,
        1,
        1,
        1,
        4,
        '2023-11-03 07:20:00'
    ),
    (
        'Incendio en edificio de Santiago',
        'Fuego en apartamento del 3er piso, bomberos en el lugar.',
        '2023-11-05 03:15:00',
        19.4517,
        -70.6970,
        1,
        1,
        2,
        200000.00,
        1,
        1,
        1,
        6,
        '2023-11-05 03:45:00'
    ),
    (
        'Inundación en calle de San Cristóbal',
        'Agua acumulada por más de 12 horas.',
        '2023-11-07 14:00:00',
        18.4167,
        -70.1000,
        1,
        0,
        0,
        30000.00,
        1,
        1,
        1,
        10,
        '2023-11-07 15:30:00'
    ),
    (
        'Protesta en la Duarte',
        'Manifestantes bloquean carretera.',
        '2023-11-10 09:00:00',
        19.3000,
        -70.2500,
        0,
        0,
        0,
        0.00,
        1,
        1,
        1,
        1,
        '2023-11-10 10:20:00'
    ),
    (
        'Atropello en Malecón de SD',
        'Vehículo golpeó a persona, conductor huyó.',
        '2023-11-12 18:30:00',
        18.4700,
        -69.9000,
        1,
        0,
        1,
        0.00,
        1,
        1,
        1,
        4,
        '2023-11-12 19:05:00'
    ),
    (
        'Derrumbe en construcción de Punta Cana',
        'Colapso de fachada en obra.',
        '2023-11-15 11:00:00',
        18.5600,
        -68.3700,
        1,
        0,
        0,
        75000.00,
        1,
        1,
        1,
        6,
        '2023-11-15 12:15:00'
    ),
    (
        'Contaminación en río Ozama',
        'Vertido de sustancias químicas.',
        '2023-11-18 08:00:00',
        18.4800,
        -69.8800,
        0,
        0,
        0,
        0.00,
        1,
        1,
        1,
        10,
        '2023-11-18 09:40:00'
    ),
    (
        'Asalto en guagua de Puerto Plata',
        'Robo colectivo en transporte público.',
        '2023-11-20 21:15:00',
        19.8000,
        -70.7000,
        1,
        0,
        0,
        8000.00,
        1,
        1,
        1,
        1,
        '2023-11-20 22:30:00'
    ),
    (
        'Fuga de gas en Los Alcarrizos',
        'Olor a gas fuerte en el sector.',
        '2023-11-25 16:45:00',
        18.5167,
        -70.0167,
        1,
        0,
        0,
        0.00,
        1,
        1,
        1,
        4,
        '2023-11-25 17:20:00'
    );

-- Etiquetas
INSERT INTO
    labels (label_name)
VALUES
    ('Accidente de tráfico'),
    ('Robo'),
    ('Incendio'),
    ('Asesinato'),
    ('Violencia'),
    ('Desastre natural');

-- Etiquetas de incidencias
INSERT INTO
    incidence_labels (incidence_id, label_id)
VALUES
    (1, 1),
    (2, 2),
    (2, 5),
    (3, 3),
    (4, 6),
    (5, 5),
    (6, 1),
    (7, 6),
    (8, 6),
    (9, 2),
    (9, 5),
    (10, 6);

-- Comentarios
INSERT INTO
    comments (incidence_id, user_id, comment_text)
VALUES
    (
        1,
        3,
        'Pasé por ahí una hora después y todavía había tráfico.'
    ),
    (1, 7, '¿Alguien sabe si ya despejaron la zona?'),
    (
        2,
        5,
        'La tienda sigue cerrada hoy, parece que fue un robo importante.'
    ),
    (
        3,
        2,
        'Confirmo, vivo cerca y el humo era muy denso.'
    ),
    (
        3,
        9,
        '¿Hay algún centro de acopio para los afectados?'
    ),
    (
        4,
        8,
        'La tubería ya fue reparada pero el agua estancada sigue ahí.'
    ),
    (5, 6, 'La protesta sigue activa, eviten la zona.'),
    (
        6,
        10,
        'El peatón fue llevado al hospital, esperemos que se recupere.'
    ),
    (
        7,
        1,
        'Ese edificio lleva años abandonado, era cuestión de tiempo.'
    ),
    (
        8,
        4,
        'Reporté esto hace meses y nadie hizo nada, ahora es peor.'
    ),
    (
        9,
        3,
        '¿Alguien tiene descripción de los asaltantes?'
    ),
    (10, 7, 'Bomberos ya están en el lugar revisando.');